version: "3.7"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - minio
  postgres:
    image: "postgres:15.7-alpine"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    expose:
      - "5432"
  minio:
    image: "bitnami/minio:2024.7.16-debian-12-r0"
    expose:
      - "9000"
      - "9001"
